/**
 * withTelecomWidgets.js
 *
 * Expo config plugin that:
 *  1. Sets App Group entitlement on the main app
 *  2. Sets NSSupportsLiveActivities in Info.plist
 *  3. Writes TelecomActivityModule native bridge files directly into
 *     ios/{ProjectName}/ using @objc + RCT_EXTERN_MODULE (no Expo
 *     autolinking or pod required — works reliably in all CI environments)
 *  4. Registers those files in the Xcode project's main app compile sources
 *  5. Ensures the bridging header imports RCTBridgeModule.h
 */

const {
  withInfoPlist,
  withEntitlementsPlist,
  withDangerousMod,
  withXcodeProject,
} = require('@expo/config-plugins');
const path = require('path');
const fs   = require('fs');

// ─── Swift: TelecomWidgetAttributes ──────────────────────────────────────────
// Must exist in BOTH the main app target (written here) AND in the widget
// extension target (targets/widgets/TelecomWidgetAttributes.swift).
// ActivityKit requires the identical ActivityAttributes type in both binaries.
const TELECOM_WIDGET_ATTRIBUTES_SWIFT = `// Auto-generated by withTelecomWidgets.js — do not edit manually.
import ActivityKit
import WidgetKit
import SwiftUI

public struct TelecomWidgetAttributes: ActivityAttributes {
  public struct ContentState: Codable, Hashable {
    public var operatorName: String
    public var phoneNumber: String
    public var internetRemaining: String
    public var internetPercent: Double
    public var internetLabel: String
    public var callsRemaining: String
    public var callsPercent: Double
    public var callsLabel: String
    public var timestamp: Double
    public init(
      operatorName:      String = "Maroc Telecom",
      phoneNumber:       String = "",
      internetRemaining: String = "0 Go",
      internetPercent:   Double = 0.0,
      internetLabel:     String = "Internet",
      callsRemaining:    String = "0h 00m",
      callsPercent:      Double = 0.0,
      callsLabel:        String = "Calls",
      timestamp:         Double = Date().timeIntervalSince1970
    ) {
      self.operatorName      = operatorName
      self.phoneNumber       = phoneNumber
      self.internetRemaining = internetRemaining
      self.internetPercent   = internetPercent
      self.internetLabel     = internetLabel
      self.callsRemaining    = callsRemaining
      self.callsPercent      = callsPercent
      self.callsLabel        = callsLabel
      self.timestamp         = timestamp
    }
  }
  public var accountId: String
  public init(accountId: String) { self.accountId = accountId }
}
`;

// ─── Swift: TelecomActivityModule ─────────────────────────────────────────────
// Classic React Native bridge via @objc + RCT_EXTERN_MODULE.
// Does NOT use ExpoModulesCore — no autolinking required.
// NativeModules.TelecomActivityModule is always available at runtime.
const TELECOM_ACTIVITY_MODULE_SWIFT = `// Auto-generated by withTelecomWidgets.js — do not edit manually.
import Foundation
import ActivityKit
import WidgetKit

@objc(TelecomActivityModule)
class TelecomActivityModule: NSObject {

  @objc static func requiresMainQueueSetup() -> Bool { return false }

  // MARK: - Widget Data

  @objc func updateWidgetData(
    _ options: NSDictionary,
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    telecomSaveToUserDefaults(options: options as? [String: Any] ?? [:])
    resolve(["status": "success"])
  }

  @objc func syncAllAccounts(
    _ options: NSDictionary,
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard let ud = UserDefaults(suiteName: "group.com.telecom.widget") else {
      reject("APP_GROUP_ERROR", "Cannot access App Group UserDefaults", nil)
      return
    }
    let dict = options as? [String: Any] ?? [:]
    ud.set(dict["activeAccountId"] as? String ?? "", forKey: "active_account_id")
    ud.set(dict["accountsJson"]    as? String ?? "[]", forKey: "all_accounts_data")
    ud.synchronize()
    if #available(iOS 14.0, *) { WidgetCenter.shared.reloadAllTimelines() }
    resolve(["status": "synced"])
  }

  // MARK: - Live Activity

  @objc func startOrUpdateActivity(
    _ options: NSDictionary,
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard #available(iOS 16.1, *) else {
      resolve(["status": "unsupported"])
      return
    }
    guard ActivityAuthorizationInfo().areActivitiesEnabled else {
      reject("ACTIVITIES_DISABLED", "Live Activities are disabled in system settings", nil)
      return
    }

    let dict      = options as? [String: Any] ?? [:]
    let accountId = dict["accountId"] as? String ?? "default"

    telecomSaveToUserDefaults(options: dict)

    let contentState = TelecomWidgetAttributes.ContentState(
      operatorName:      dict["operator"]          as? String ?? "Maroc Telecom",
      phoneNumber:       dict["phoneNumber"]        as? String ?? "",
      internetRemaining: dict["internetRemaining"]  as? String ?? "0 Go",
      internetPercent:   dict["internetPercent"]    as? Double ?? 0.0,
      internetLabel:     dict["internetLabel"]      as? String ?? "Internet",
      callsRemaining:    dict["callsRemaining"]     as? String ?? "0h 00m",
      callsPercent:      dict["callsPercent"]       as? Double ?? 0.0,
      callsLabel:        dict["callsLabel"]         as? String ?? "Calls",
      timestamp:         dict["timestamp"]          as? Double ?? Date().timeIntervalSince1970
    )
    let attributes = TelecomWidgetAttributes(accountId: accountId)

    if #available(iOS 16.2, *) {
      if let existing = Activity<TelecomWidgetAttributes>.activities
          .first(where: { $0.attributes.accountId == accountId }) {
        Task {
          await existing.update(ActivityContent(state: contentState, staleDate: nil))
          resolve(["status": "updated", "id": existing.id])
        }
      } else {
        Task {
          for a in Activity<TelecomWidgetAttributes>.activities {
            await a.end(nil, dismissalPolicy: .immediate)
          }
          do {
            let activity = try Activity.request(
              attributes: attributes,
              content:    ActivityContent(state: contentState, staleDate: nil),
              pushType:   nil
            )
            resolve(["status": "started", "id": activity.id])
          } catch {
            reject("REQUEST_FAILED", error.localizedDescription, error as NSError)
          }
        }
      }
    } else {
      // iOS 16.1
      if let existing = Activity<TelecomWidgetAttributes>.activities
          .first(where: { $0.attributes.accountId == accountId }) {
        Task {
          await existing.update(using: contentState)
          resolve(["status": "updated", "id": existing.id])
        }
      } else {
        Task {
          do {
            let activity = try Activity.request(
              attributes:   attributes,
              contentState: contentState,
              pushType:     nil
            )
            resolve(["status": "started", "id": activity.id])
          } catch {
            reject("REQUEST_FAILED", error.localizedDescription, error as NSError)
          }
        }
      }
    }
  }

  @objc func stopActivity(
    _ resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard #available(iOS 16.1, *) else { resolve(["status": "unsupported"]); return }
    Task {
      for a in Activity<TelecomWidgetAttributes>.activities {
        if #available(iOS 16.2, *) {
          await a.end(nil, dismissalPolicy: .immediate)
        } else {
          await a.end(using: nil, dismissalPolicy: .immediate)
        }
      }
      resolve(["status": "stopped"])
    }
  }

  @objc func isActivityActive(
    _ resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard #available(iOS 16.1, *) else { resolve(false); return }
    resolve(!Activity<TelecomWidgetAttributes>.activities.isEmpty)
  }
}

// MARK: - Shared UserDefaults helper

private func telecomSaveToUserDefaults(options: [String: Any]) {
  guard let ud = UserDefaults(suiteName: "group.com.telecom.widget") else { return }
  ud.set(options["operator"]          as? String ?? "Maroc Telecom", forKey: "widget_operator")
  ud.set(options["phoneNumber"]       as? String ?? "",              forKey: "widget_phone")
  ud.set(options["internetRemaining"] as? String ?? "0 Go",          forKey: "widget_internet")
  ud.set(options["internetPercent"]   as? Double ?? 0.0,             forKey: "widget_internet_percent")
  ud.set(options["internetLabel"]     as? String ?? "Internet",      forKey: "widget_internet_label")
  ud.set(options["callsRemaining"]    as? String ?? "0h 00m",        forKey: "widget_calls")
  ud.set(options["callsPercent"]      as? Double ?? 0.0,             forKey: "widget_calls_percent")
  ud.set(options["callsLabel"]        as? String ?? "Calls",         forKey: "widget_calls_label")
  ud.set(options["mainBalance"]       as? String ?? "",              forKey: "widget_main_balance")
  ud.set(
    options["timestamp"] as? Double ?? Date().timeIntervalSince1970,
    forKey: "widget_timestamp"
  )
  ud.synchronize()
  if #available(iOS 14.0, *) { WidgetCenter.shared.reloadAllTimelines() }
}
`;

// ─── Objective-C: RCT_EXTERN_MODULE bridge ────────────────────────────────────
const TELECOM_ACTIVITY_MODULE_M = `// Auto-generated by withTelecomWidgets.js — do not edit manually.
#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(TelecomActivityModule, NSObject)

RCT_EXTERN_METHOD(updateWidgetData:(NSDictionary *)options
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(syncAllAccounts:(NSDictionary *)options
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(startOrUpdateActivity:(NSDictionary *)options
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(stopActivity:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(isActivityActive:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)

@end
`;

// ─── Source file manifest ─────────────────────────────────────────────────────
const NATIVE_FILES = [
  { name: 'TelecomWidgetAttributes.swift', content: TELECOM_WIDGET_ATTRIBUTES_SWIFT },
  { name: 'TelecomActivityModule.swift',   content: TELECOM_ACTIVITY_MODULE_SWIFT   },
  { name: 'TelecomActivityModule.m',       content: TELECOM_ACTIVITY_MODULE_M       },
];

// ─── Plugin Step 1: Write source files to ios/{ProjectName}/ ─────────────────
function withTelecomNativeFiles(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = config.modRequest.platformProjectRoot; // …/ios
      const projectName = config.modRequest.projectName;         // TelecomWidget
      const destDir     = path.join(projectRoot, projectName);
      fs.mkdirSync(destDir, { recursive: true });

      for (const { name, content } of NATIVE_FILES) {
        fs.writeFileSync(path.join(destDir, name), content, 'utf8');
      }

      // Ensure bridging header imports RCTBridgeModule.h (idempotent)
      const bridgingHeaderPath = path.join(destDir, `${projectName}-Bridging-Header.h`);
      if (fs.existsSync(bridgingHeaderPath)) {
        let header = fs.readFileSync(bridgingHeaderPath, 'utf8');
        if (!header.includes('<React/RCTBridgeModule.h>')) {
          header += '\n#import <React/RCTBridgeModule.h>\n';
          fs.writeFileSync(bridgingHeaderPath, header, 'utf8');
        }
      }

      console.log(`[withTelecomWidgets] Native bridge files written to ${destDir}`);
      return config;
    },
  ]);
}

// ─── Plugin Step 2: Register files in Xcode project compile sources ───────────
function withTelecomXcodeFiles(config) {
  return withXcodeProject(config, (config) => {
    const xcodeProject = config.modResults;
    const projectName  = config.modRequest.projectName;
    const targetKey    = xcodeProject.findTargetKey(projectName);

    if (!targetKey) {
      console.warn(`[withTelecomWidgets] Xcode target not found: ${projectName}`);
      return config;
    }

    // Locate the PBXGroup that represents the main app source folder
    const pbxGroups = xcodeProject.hash.project.objects['PBXGroup'] ?? {};
    let appGroupKey = null;
    for (const [key, group] of Object.entries(pbxGroups)) {
      if (key.endsWith('_comment')) continue;
      if (group.path === projectName || group.name === projectName) {
        appGroupKey = key;
        break;
      }
    }

    if (!appGroupKey) {
      console.warn(`[withTelecomWidgets] PBXGroup not found for "${projectName}". Skipping.`);
      return config;
    }

    // Collect paths already in the project to avoid duplicate entries
    const existingPaths = new Set(
      Object.values(xcodeProject.hash.project.objects['PBXFileReference'] ?? {})
        .filter(r => r && typeof r === 'object' && r.path)
        .map(r => r.path)
    );

    for (const { name } of NATIVE_FILES) {
      const filePath = `${projectName}/${name}`;
      if (existingPaths.has(name) || existingPaths.has(filePath)) {
        console.log(`[withTelecomWidgets] ${name} already registered — skipping.`);
        continue;
      }
      xcodeProject.addSourceFile(filePath, { target: targetKey }, appGroupKey);
      console.log(`[withTelecomWidgets] Added ${filePath} to target "${projectName}".`);
    }

    return config;
  });
}

// ─── Main export ──────────────────────────────────────────────────────────────
const withTelecomWidgets = (config) => {
  // 1. App Group entitlement
  config = withEntitlementsPlist(config, (c) => {
    c.modResults['com.apple.security.application-groups'] = ['group.com.telecom.widget'];
    return c;
  });

  // 2. Info.plist — Live Activities support
  config = withInfoPlist(config, (c) => {
    c.modResults['NSSupportsLiveActivities']               = true;
    c.modResults['NSSupportsLiveActivitiesFrequentUpdates'] = true;
    return c;
  });

  // 3. Write Swift + ObjC source files into the iOS project
  config = withTelecomNativeFiles(config);

  // 4. Register them in the Xcode project compile sources
  config = withTelecomXcodeFiles(config);

  return config;
};

module.exports = withTelecomWidgets;
